export const stepsArray = [
  [
    "Thinking",
    "Crafting constraints",
    "Piecing together",
    "Evaluating options",
    "Thought for 8 seconds",
  ],
  [
    "Making a list",
    "Checking the requirements",
    "Reviewing the tasks",
    "Starting with the first item",
    "Thought for 12 seconds",
  ],
  [
    "Thinking about formulas",
    "Writing down equations",
    "Testing assumptions",
    "Checking for errors",
    "Thought for 10 seconds",
  ],
  [
    "Planning the steps",
    "Gathering materials",
    "Setting up the workspace",
    "Starting the first task",
    "Thought for 15 seconds",
  ],
  [
    "Brainstorming ideas",
    "Sketching concepts",
    "Choosing the best approach",
    "Refining the design",
    "Thought for 8 seconds",
  ],
  [
    "Organizing thoughts",
    "Writing down key points",
    "Prioritizing tasks",
    "Setting deadlines",
    "Thought for 9 seconds",
  ],
  [
    "Researching options",
    "Reading through articles",
    "Taking notes",
    "Summarizing findings",
    "Thought for 14 seconds",
  ],
  [
    "Analyzing data",
    "Creating graphs",
    "Identifying trends",
    "Drawing conclusions",
    "Thought for 11 seconds",
  ],
  [
    "Calculating values",
    "Double-checking formulas",
    "Making adjustments",
    "Verifying results",
    "Thought for 8 seconds",
  ],
  [
    "Writing the code",
    "Testing functions",
    "Debugging errors",
    "Refining the solution",
    "Thought for 16 seconds",
  ],
  [
    "Drawing a diagram",
    "Labeling parts",
    "Connecting the components",
    "Reviewing the layout",
    "Thought for 9 seconds",
  ],
  [
    "Taking a break",
    "Clearing the mind",
    "Recharging energy",
    "Returning with focus",
    "Thought for 7 seconds",
  ],
  [
    "Setting goals",
    "Breaking down tasks",
    "Scheduling time",
    "Getting to work",
    "Thought for 10 seconds",
  ],
  [
    "Designing the structure",
    "Writing the outline",
    "Filling in the details",
    "Finalizing the draft",
    "Thought for 12 seconds",
  ],
  [
    "Creating a plan",
    "Listing priorities",
    "Assigning tasks",
    "Tracking progress",
    "Thought for 13 seconds",
  ],
  [
    "Reviewing feedback",
    "Making revisions",
    "Polishing the content",
    "Submitting the work",
    "Thought for 8 seconds",
  ],
];
